name: Action

on:
  workflow_run:
    workflows: ["Test"]
    types:
      - completed

jobs:
   build:
      if: ${{ github.event.workflow_run.conclusion == 'success' }}
      runs-on: ${{ matrix.os }}
      strategy:
         fail-fast: false
         matrix:
          os: [macos-latest, windows-latest, ubuntu-latest]

      steps:
        - uses: actions/checkout@v2
        -
          name: Configure
          run: cmake -S . -B build -DCMAKE_BUILD_TYPE=Release
        -
          name: Build
          run: cmake --build build --config Release --target Calculator -j2
        -
          name: Upload
          uses: actions/upload-artifact@main
          with:
             name: ${{ matrix.os }}
             path: build/app/Calculator*
